# Generated by Django 4.1.7 on 2023-02-20 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_manager_email', models.EmailField(max_length=79)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('coffee_type', models.CharField(choices=[('For Premium', 'For Premium Users'), ('For regular', 'For Regular Users')], default='For regular', max_length=79)),
                ('main_photo', models.ImageField(upload_to='coffeeTypes/')),
                ('photo_1', models.ImageField(upload_to='coffeeTypes/')),
                ('photo_2', models.ImageField(upload_to='coffeeTypes/')),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
