# Generated by Django 4.0.5 on 2023-07-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=79)),
            ],
        ),
    ]
