# Generated by Django 4.0.5 on 2023-07-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_types', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coffee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coffee_types.coffee'),
        ),
    ]
