# Generated by Django 4.0.5 on 2023-07-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_types', '0003_order_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
