# Generated by Django 4.0.5 on 2023-07-28 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coffee_types', '0004_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
